### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by BenIraa** [Divyansh6799/Library-Management-system#1]
Please how can I get the .sql file of this project exported

**Comment by Divyansh6799** [comment]
1- So first thing is to do that copy raw content of my database file and create the same database file and paste on it.
2- Then you have the same database file as We have.
3-  Export the database file into your Oracle Sql Developer by Follow these [Steps:-](https://docs.oracle.com/cd/E17781_01/server.112/e18804/impexp.htm#ADMQS272)
4- Connect the database with your Project.

Thank You.

**Comment by BenIraa** [comment]
Thanks ! its working
